/*=============================================================================
  FINSERV DEMO — Step 04: Internal Stage, File Format & COPY INTO
  Loads CSV files generated by 03_csv_generator_and_s3_upload.py into
  landing tables via an internal stage and COPY INTO.

  Prerequisites:
    1. Run: pip install faker
    2. Run: python3 03_csv_generator_and_s3_upload.py
       → produces ./csv_output/customers.csv, transactions.csv, risk_assessments.csv
=============================================================================*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINSERV_WH;
USE DATABASE FINSERV_DB;
USE SCHEMA RAW;

-- ============================================================
-- 1. FILE FORMAT
-- ============================================================

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE                 = CSV
    FIELD_DELIMITER      = ','
    SKIP_HEADER          = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF              = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL  = TRUE
    TRIM_SPACE           = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    COMMENT              = 'Standard CSV format for local file ingestion';


-- ============================================================
-- 2. INTERNAL STAGE
-- ============================================================

CREATE STAGE IF NOT EXISTS CSV_STAGE
    FILE_FORMAT = CSV_FORMAT
    COMMENT     = 'Internal stage for CSV file ingestion';

-- Upload CSV files (run these from SnowSQL or snowflake CLI):
--   PUT file://./csv_output/customers.csv        @RAW.CSV_STAGE/customers        AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
--   PUT file://./csv_output/transactions.csv     @RAW.CSV_STAGE/transactions     AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
--   PUT file://./csv_output/risk_assessments.csv @RAW.CSV_STAGE/risk_assessments AUTO_COMPRESS=TRUE OVERWRITE=TRUE;

-- Verify staged files:
-- LIST @CSV_STAGE;


-- ============================================================
-- 3. LANDING TABLES (CSV targets, separate from BASE tables)
-- ============================================================

CREATE TABLE IF NOT EXISTS CUSTOMERS_S3 (
    FIRST_NAME         VARCHAR(50),
    LAST_NAME          VARCHAR(50),
    EMAIL              VARCHAR(100),
    PHONE              VARCHAR(30),
    DATE_OF_BIRTH      DATE,
    CITY               VARCHAR(50),
    STATE              VARCHAR(50),
    COUNTRY            VARCHAR(50),
    ANNUAL_INCOME      NUMBER(12,2),
    EMPLOYMENT_STATUS  VARCHAR(20),
    CREDIT_SCORE       NUMBER(4,0),
    SIGNUP_DATE        TIMESTAMP_NTZ,
    _LOADED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE       VARCHAR(500) DEFAULT METADATA$FILENAME
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS_S3 (
    ACCOUNT_ID      NUMBER,
    TXN_DATE        TIMESTAMP_NTZ,
    TXN_TYPE        VARCHAR(15),
    AMOUNT          NUMBER(12,2),
    MERCHANT_NAME   VARCHAR(100),
    CATEGORY        VARCHAR(30),
    CHANNEL         VARCHAR(15),
    IS_FLAGGED      BOOLEAN,
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR(500) DEFAULT METADATA$FILENAME
);

CREATE TABLE IF NOT EXISTS RISK_ASSESSMENTS_S3 (
    CUSTOMER_ID     NUMBER,
    ASSESSED_AT     TIMESTAMP_NTZ,
    RISK_DATA_RAW   VARCHAR(16777216),
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR(500) DEFAULT METADATA$FILENAME
);


-- ============================================================
-- 4. COPY INTO — Load from Internal Stage
-- ============================================================

-- Customers
COPY INTO CUSTOMERS_S3 (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH,
                        CITY, STATE, COUNTRY, ANNUAL_INCOME, EMPLOYMENT_STATUS,
                        CREDIT_SCORE, SIGNUP_DATE)
FROM @CSV_STAGE/customers
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- Transactions
COPY INTO TRANSACTIONS_S3 (ACCOUNT_ID, TXN_DATE, TXN_TYPE, AMOUNT,
                            MERCHANT_NAME, CATEGORY, CHANNEL, IS_FLAGGED)
FROM @CSV_STAGE/transactions
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- Risk Assessments (JSON column loaded as raw text, parsed in view below)
COPY INTO RISK_ASSESSMENTS_S3 (CUSTOMER_ID, ASSESSED_AT, RISK_DATA_RAW)
FROM @CSV_STAGE/risk_assessments
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;


-- ============================================================
-- 5. POST-LOAD: Parse VARIANT from CSV Text
-- ============================================================
-- Convert RISK_DATA_RAW (string) → VARIANT for downstream queries

CREATE OR REPLACE VIEW RISK_ASSESSMENTS_S3_PARSED AS
SELECT
    CUSTOMER_ID,
    ASSESSED_AT,
    TRY_PARSE_JSON(RISK_DATA_RAW) AS RISK_DATA,
    _LOADED_AT,
    _SOURCE_FILE
FROM RISK_ASSESSMENTS_S3;


-- ============================================================
-- 6. MERGE INTO BASE — Feed CSV data into the medallion pipeline
-- ============================================================
-- The downstream pipeline (streams → curated → consumption) reads from BASE.
-- These MERGEs push CSV-ingested data into BASE so it flows through automatically.

-- 6a. Customers: MERGE on EMAIL (natural key; S3 data has no CUSTOMER_ID)
MERGE INTO BASE.CUSTOMERS tgt
USING (
    SELECT DISTINCT
        FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH,
        CITY, STATE, COUNTRY, ANNUAL_INCOME, EMPLOYMENT_STATUS,
        CREDIT_SCORE, SIGNUP_DATE
    FROM RAW.CUSTOMERS_S3
) src
ON tgt.EMAIL = src.EMAIL
WHEN MATCHED THEN UPDATE SET
    tgt.FIRST_NAME        = src.FIRST_NAME,
    tgt.LAST_NAME         = src.LAST_NAME,
    tgt.PHONE             = src.PHONE,
    tgt.CITY              = src.CITY,
    tgt.STATE             = src.STATE,
    tgt.COUNTRY           = src.COUNTRY,
    tgt.ANNUAL_INCOME     = src.ANNUAL_INCOME,
    tgt.EMPLOYMENT_STATUS = src.EMPLOYMENT_STATUS,
    tgt.CREDIT_SCORE      = src.CREDIT_SCORE
WHEN NOT MATCHED THEN INSERT (
    FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH,
    CITY, STATE, COUNTRY, ANNUAL_INCOME, EMPLOYMENT_STATUS,
    CREDIT_SCORE, SIGNUP_DATE
) VALUES (
    src.FIRST_NAME, src.LAST_NAME, src.EMAIL, src.PHONE, src.DATE_OF_BIRTH,
    src.CITY, src.STATE, src.COUNTRY, src.ANNUAL_INCOME, src.EMPLOYMENT_STATUS,
    src.CREDIT_SCORE, src.SIGNUP_DATE
);

-- 6b. Transactions: INSERT only (transactions are immutable, no natural key to match)
INSERT INTO BASE.TRANSACTIONS (ACCOUNT_ID, TXN_DATE, TXN_TYPE, AMOUNT,
                                MERCHANT_NAME, CATEGORY, CHANNEL, IS_FLAGGED)
SELECT ACCOUNT_ID, TXN_DATE, TXN_TYPE, AMOUNT,
       MERCHANT_NAME, CATEGORY, CHANNEL, IS_FLAGGED
FROM RAW.TRANSACTIONS_S3;

-- 6c. Risk Assessments: MERGE on CUSTOMER_ID + ASSESSED_AT (composite key)
MERGE INTO BASE.RISK_ASSESSMENTS tgt
USING (
    SELECT
        CUSTOMER_ID,
        ASSESSED_AT,
        TRY_PARSE_JSON(RISK_DATA_RAW) AS RISK_DATA
    FROM RAW.RISK_ASSESSMENTS_S3
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID AND tgt.ASSESSED_AT = src.ASSESSED_AT
WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID, ASSESSED_AT, RISK_DATA
) VALUES (
    src.CUSTOMER_ID, src.ASSESSED_AT, src.RISK_DATA
);


-- ============================================================
-- 7. SNOWPIPE REFERENCE (Auto-Ingest from S3 — requires real S3 bucket)
-- ============================================================
-- The Snowpipe definitions below show the auto-ingest pattern for continuous
-- loading from S3 via SQS event notifications. They require:
--   1. A real S3 bucket with event notifications configured
--   2. A storage integration (CREATE STORAGE INTEGRATION ...)
--   3. An external stage pointing to the S3 bucket
--
-- To enable: replace the internal stage above with an external stage,
-- uncomment these pipes, and configure S3 event notifications using the
-- notification_channel ARN from SHOW PIPES.
/*
CREATE STORAGE INTEGRATION IF NOT EXISTS S3_FINSERV_INTEGRATION
    TYPE                  = EXTERNAL_STAGE
    STORAGE_PROVIDER      = 'S3'
    STORAGE_AWS_ROLE_ARN  = 'arn:aws:iam::123456789012:role/snowflake-finserv-role'
    ENABLED               = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://your-finserv-bucket/finserv-demo/');

CREATE STAGE IF NOT EXISTS S3_FINSERV_STAGE
    STORAGE_INTEGRATION = S3_FINSERV_INTEGRATION
    URL                 = 's3://your-finserv-bucket/finserv-demo/'
    FILE_FORMAT         = CSV_FORMAT;

CREATE PIPE IF NOT EXISTS PIPE_CUSTOMERS_S3
    AUTO_INGEST = TRUE
    COMMENT     = 'Auto-ingest customer CSVs from S3'
AS
    COPY INTO CUSTOMERS_S3 (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH,
                            CITY, STATE, COUNTRY, ANNUAL_INCOME, EMPLOYMENT_STATUS,
                            CREDIT_SCORE, SIGNUP_DATE)
    FROM @S3_FINSERV_STAGE/customers
    FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
    ON_ERROR = 'CONTINUE';

CREATE PIPE IF NOT EXISTS PIPE_TRANSACTIONS_S3
    AUTO_INGEST = TRUE
    COMMENT     = 'Auto-ingest transaction CSVs from S3'
AS
    COPY INTO TRANSACTIONS_S3 (ACCOUNT_ID, TXN_DATE, TXN_TYPE, AMOUNT,
                                MERCHANT_NAME, CATEGORY, CHANNEL, IS_FLAGGED)
    FROM @S3_FINSERV_STAGE/transactions
    FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
    ON_ERROR = 'CONTINUE';

CREATE PIPE IF NOT EXISTS PIPE_RISK_ASSESSMENTS_S3
    AUTO_INGEST = TRUE
    COMMENT     = 'Auto-ingest risk assessment CSVs from S3'
AS
    COPY INTO RISK_ASSESSMENTS_S3 (CUSTOMER_ID, ASSESSED_AT, RISK_DATA_RAW)
    FROM @S3_FINSERV_STAGE/risk_assessments
    FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
    ON_ERROR = 'CONTINUE';

-- After creating pipes, get SQS notification channel ARNs:
-- SHOW PIPES IN SCHEMA RAW;
*/


-- ============================================================
-- 8. VERIFY
-- ============================================================

-- Landing table counts (from COPY INTO)
SELECT 'CUSTOMERS_S3'        AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS_S3
UNION ALL SELECT 'TRANSACTIONS_S3',    COUNT(*) FROM TRANSACTIONS_S3
UNION ALL SELECT 'RISK_ASSESSMENTS_S3', COUNT(*) FROM RISK_ASSESSMENTS_S3
ORDER BY TABLE_NAME;

-- BASE table counts (after MERGE — should include CSV-sourced rows)
SELECT 'BASE.CUSTOMERS'        AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM BASE.CUSTOMERS
UNION ALL SELECT 'BASE.TRANSACTIONS',    COUNT(*) FROM BASE.TRANSACTIONS
UNION ALL SELECT 'BASE.RISK_ASSESSMENTS', COUNT(*) FROM BASE.RISK_ASSESSMENTS
ORDER BY TABLE_NAME;
