/*=============================================================================
  FINSERV DEMO — Step 18: Monitoring & Validation
  Row counts, stream status, DT health, pipe history, and data quality checks.
  Run this after deploying scripts 01-08 to validate the full pipeline.
=============================================================================*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINSERV_WH;
USE DATABASE FINSERV_DB;

-- ============================================================
-- 1. ROW COUNTS ACROSS ALL LAYERS
-- ============================================================

SELECT '>>> ROW COUNTS <<<' AS SECTION;

SELECT 'BASE.CUSTOMERS'             AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM BASE.CUSTOMERS
UNION ALL SELECT 'BASE.ACCOUNTS',             COUNT(*) FROM BASE.ACCOUNTS
UNION ALL SELECT 'BASE.TRANSACTIONS',         COUNT(*) FROM BASE.TRANSACTIONS
UNION ALL SELECT 'BASE.RISK_ASSESSMENTS',     COUNT(*) FROM BASE.RISK_ASSESSMENTS
UNION ALL SELECT 'BASE.MARKET_DATA',          COUNT(*) FROM BASE.MARKET_DATA
UNION ALL SELECT 'BASE.SUPPORT_TICKETS',      COUNT(*) FROM BASE.SUPPORT_TICKETS
UNION ALL SELECT 'BASE.COMPLIANCE_DOCUMENTS', COUNT(*) FROM BASE.COMPLIANCE_DOCUMENTS
UNION ALL SELECT 'CURATED.DT_CUSTOMER_PROFILE',    COUNT(*) FROM CURATED.DT_CUSTOMER_PROFILE
UNION ALL SELECT 'CURATED.DT_TRANSACTION_ENRICHED', COUNT(*) FROM CURATED.DT_TRANSACTION_ENRICHED
UNION ALL SELECT 'CURATED.DT_SUPPORT_ENRICHED',    COUNT(*) FROM CURATED.DT_SUPPORT_ENRICHED
UNION ALL SELECT 'CURATED.DT_RISK_FACTORS_PARSED', COUNT(*) FROM CURATED.DT_RISK_FACTORS_PARSED
UNION ALL SELECT 'CONSUMPTION.DT_CUSTOMER_360',           COUNT(*) FROM CONSUMPTION.DT_CUSTOMER_360
UNION ALL SELECT 'CONSUMPTION.DT_DAILY_FINANCIAL_METRICS', COUNT(*) FROM CONSUMPTION.DT_DAILY_FINANCIAL_METRICS
UNION ALL SELECT 'CONSUMPTION.DT_RISK_DASHBOARD',         COUNT(*) FROM CONSUMPTION.DT_RISK_DASHBOARD
UNION ALL SELECT 'CONSUMPTION.DT_CHANNEL_PERFORMANCE',    COUNT(*) FROM CONSUMPTION.DT_CHANNEL_PERFORMANCE
UNION ALL SELECT 'CONSUMPTION.DT_CHURN_FEATURES',         COUNT(*) FROM CONSUMPTION.DT_CHURN_FEATURES
UNION ALL SELECT 'CONSUMPTION.DT_MONTHLY_REVENUE',        COUNT(*) FROM CONSUMPTION.DT_MONTHLY_REVENUE
ORDER BY OBJECT_NAME;


-- ============================================================
-- 2. STREAM STATUS
-- ============================================================

SELECT '>>> STREAM STATUS <<<' AS SECTION;

SELECT 'CUSTOMERS_STREAM'       AS STREAM, SYSTEM$STREAM_HAS_DATA('RAW.CUSTOMERS_STREAM')       AS HAS_DATA
UNION ALL SELECT 'ACCOUNTS_STREAM',          SYSTEM$STREAM_HAS_DATA('RAW.ACCOUNTS_STREAM')
UNION ALL SELECT 'TRANSACTIONS_STREAM',      SYSTEM$STREAM_HAS_DATA('RAW.TRANSACTIONS_STREAM')
UNION ALL SELECT 'RISK_ASSESSMENTS_STREAM',  SYSTEM$STREAM_HAS_DATA('RAW.RISK_ASSESSMENTS_STREAM')
UNION ALL SELECT 'MARKET_DATA_STREAM',       SYSTEM$STREAM_HAS_DATA('RAW.MARKET_DATA_STREAM')
UNION ALL SELECT 'SUPPORT_TICKETS_STREAM',   SYSTEM$STREAM_HAS_DATA('RAW.SUPPORT_TICKETS_STREAM')
UNION ALL SELECT 'COMPLIANCE_DOCS_STREAM',   SYSTEM$STREAM_HAS_DATA('RAW.COMPLIANCE_DOCS_STREAM');


-- ============================================================
-- 3. DYNAMIC TABLE REFRESH STATUS
-- ============================================================

SELECT '>>> DYNAMIC TABLE STATUS <<<' AS SECTION;

SELECT
    NAME,
    SCHEMA_NAME,
    TARGET_LAG,
    REFRESH_MODE,
    SCHEDULING_STATE
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES())
WHERE DATABASE_NAME = 'FINSERV_DB'
ORDER BY SCHEMA_NAME, NAME;


-- ============================================================
-- 4. DYNAMIC TABLE REFRESH HISTORY (last hour)
-- ============================================================

SELECT '>>> DT REFRESH HISTORY <<<' AS SECTION;

SELECT
    NAME,
    SCHEMA_NAME,
    STATE,
    STATE_MESSAGE,
    REFRESH_START_TIME,
    REFRESH_END_TIME,
    DATEDIFF('second', REFRESH_START_TIME, REFRESH_END_TIME) AS DURATION_SEC
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
    NAME_PREFIX => 'FINSERV_DB.'
))
WHERE REFRESH_START_TIME >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY REFRESH_START_TIME DESC
LIMIT 30;


-- ============================================================
-- 5. TASK DAG STATUS
-- ============================================================

SELECT '>>> TASK DAG <<<' AS SECTION;

SELECT
    NAME,
    STATE,
    SCHEDULE,
    PREDECESSORS,
    CONDITION
FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
    TASK_NAME => 'FINSERV_DB.RAW.TASK_ROOT_SCHEDULER',
    RECURSIVE => TRUE
));

-- Recent task history
SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -2, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 20
))
ORDER BY SCHEDULED_TIME DESC;


-- ============================================================
-- 6. CSV / S3 INGESTION STATUS
-- ============================================================

SELECT '>>> S3 LANDING TABLE COUNTS <<<' AS SECTION;

SELECT 'RAW.CUSTOMERS_S3'        AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.CUSTOMERS_S3
UNION ALL SELECT 'RAW.TRANSACTIONS_S3',    COUNT(*) FROM RAW.TRANSACTIONS_S3
UNION ALL SELECT 'RAW.RISK_ASSESSMENTS_S3', COUNT(*) FROM RAW.RISK_ASSESSMENTS_S3
ORDER BY TABLE_NAME;


-- ============================================================
-- 7. S3 → BASE MERGE VALIDATION
-- ============================================================

SELECT '>>> S3 → BASE MERGE HEALTH <<<' AS SECTION;

-- Customers: every S3 email should exist in BASE after MERGE
SELECT 'Unmerged S3 customers (email not in BASE)' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM RAW.CUSTOMERS_S3 s
LEFT JOIN BASE.CUSTOMERS b ON s.EMAIL = b.EMAIL
WHERE b.EMAIL IS NULL;

-- Transactions: S3 row count should be <= the increase in BASE
SELECT 'S3 transaction rows loaded' AS CHECK_NAME,
       COUNT(*) AS ROW_COUNT
FROM RAW.TRANSACTIONS_S3;

-- Risk assessments: every S3 (CUSTOMER_ID, ASSESSED_AT) pair should be in BASE
SELECT 'Unmerged S3 risk assessments' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM RAW.RISK_ASSESSMENTS_S3 s
LEFT JOIN BASE.RISK_ASSESSMENTS b
    ON s.CUSTOMER_ID = b.CUSTOMER_ID
   AND s.ASSESSED_AT = b.ASSESSED_AT
WHERE b.ASSESSMENT_ID IS NULL;

-- COPY INTO history for S3 landing tables (last 24h)
SELECT '>>> COPY HISTORY (S3 tables) <<<' AS SECTION;

SELECT
    TABLE_NAME,
    FILE_NAME,
    ROW_COUNT,
    STATUS,
    FIRST_ERROR_MESSAGE,
    LAST_LOAD_TIME
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW.CUSTOMERS_S3',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC
LIMIT 10;


-- ============================================================
-- 8. DATA QUALITY SPOT CHECKS
-- ============================================================

SELECT '>>> DATA QUALITY CHECKS <<<' AS SECTION;

-- Check for NULL customer IDs in transactions
SELECT 'NULL account_id in transactions' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM BASE.TRANSACTIONS
WHERE ACCOUNT_ID IS NULL;

-- Check for orphan accounts (no matching customer)
SELECT 'Orphan accounts (no customer)' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM BASE.ACCOUNTS a
LEFT JOIN BASE.CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

-- Check for invalid risk scores
SELECT 'Risk scores out of range (0-100)' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM BASE.RISK_ASSESSMENTS
WHERE RISK_DATA:risk_score::INT < 0 OR RISK_DATA:risk_score::INT > 100;

-- Check for negative balances in accounts
SELECT 'Negative account balances' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM BASE.ACCOUNTS
WHERE BALANCE < 0;

-- Check for future transaction dates
SELECT 'Future transactions' AS CHECK_NAME,
       COUNT(*) AS ISSUE_COUNT
FROM BASE.TRANSACTIONS
WHERE TXN_DATE > CURRENT_TIMESTAMP();

-- Check churn label distribution
SELECT 'Churn feature distribution' AS CHECK_NAME,
       IS_CHURNED,
       COUNT(*) AS COUNT
FROM CONSUMPTION.DT_CHURN_FEATURES
GROUP BY IS_CHURNED;


-- ============================================================
-- 9. CONSUMPTION LAYER SAMPLE DATA
-- ============================================================

SELECT '>>> SAMPLE: Customer 360 <<<' AS SECTION;
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_SEGMENT,
       TOTAL_BALANCE, TOTAL_TRANSACTIONS, LATEST_RISK_SCORE, TOTAL_TICKETS
FROM CONSUMPTION.DT_CUSTOMER_360
ORDER BY TOTAL_BALANCE DESC
LIMIT 10;

SELECT '>>> SAMPLE: Daily Metrics <<<' AS SECTION;
SELECT * FROM CONSUMPTION.DT_DAILY_FINANCIAL_METRICS
ORDER BY METRIC_DATE DESC
LIMIT 10;

SELECT '>>> SAMPLE: Channel Performance <<<' AS SECTION;
SELECT CHANNEL,
       SUM(TRANSACTION_COUNT) AS TOTAL_TXNS,
       ROUND(SUM(TOTAL_VOLUME), 2) AS TOTAL_VOLUME,
       ROUND(AVG(AVG_AMOUNT), 2) AS AVG_TXN
FROM CONSUMPTION.DT_CHANNEL_PERFORMANCE
GROUP BY CHANNEL
ORDER BY TOTAL_VOLUME DESC;

SELECT '>>> MONITORING COMPLETE <<<' AS SECTION;
