/*=============================================================================
  FINSERV DEMO — Step 20: Performance Exploration & Optimization
  Hands-on module demonstrating Snowflake performance concepts:
    1.  EXPLAIN plans & query profiling
    2.  Warehouse sizing & scaling
    3.  Micro-partitions & clustering metadata
    4.  Automatic clustering
    5.  Search optimization
    6.  Result & metadata caching
    7.  Warehouse utilization & spilling
    8.  Query acceleration service
    9.  Resource monitors
    10. Performance comparison summary
=============================================================================*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINSERV_WH;
USE DATABASE FINSERV_DB;


-- ============================================================
-- 1. EXPLAIN PLANS & QUERY PROFILING
--    Read execution plans before running expensive queries.
-- ============================================================

EXPLAIN USING TABULAR
SELECT
    cp.CUSTOMER_ID, cp.FIRST_NAME, cp.LAST_NAME,
    cp.TOTAL_BALANCE, cp.LATEST_RISK_SCORE,
    te.TXN_COUNT, te.TOTAL_SPENT
FROM CURATED.DT_CUSTOMER_PROFILE cp
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS TXN_COUNT, SUM(AMOUNT) AS TOTAL_SPENT
    FROM CURATED.DT_TRANSACTION_ENRICHED
    GROUP BY CUSTOMER_ID
) te ON cp.CUSTOMER_ID = te.CUSTOMER_ID
WHERE cp.TOTAL_BALANCE > 100000;

EXPLAIN USING JSON
SELECT CATEGORY, CHANNEL, COUNT(*) AS TXN_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM BASE.TRANSACTIONS
GROUP BY CATEGORY, CHANNEL
ORDER BY TOTAL_AMOUNT DESC;


-- ============================================================
-- 2. WAREHOUSE SIZING & SCALING
--    Compare warehouse sizes and understand multi-cluster.
-- ============================================================

SHOW WAREHOUSES LIKE 'FINSERV%';

SELECT
    WAREHOUSE_NAME, WAREHOUSE_SIZE, WAREHOUSE_TYPE,
    AUTO_SUSPEND, AUTO_RESUME, MIN_CLUSTER_COUNT, MAX_CLUSTER_COUNT,
    SCALING_POLICY
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSES
WHERE WAREHOUSE_NAME LIKE 'FINSERV%'
  AND DELETED IS NULL;

CREATE WAREHOUSE IF NOT EXISTS FINSERV_WH_SMALL
    WAREHOUSE_SIZE  = 'SMALL'
    AUTO_SUSPEND    = 60
    AUTO_RESUME     = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT         = 'Performance test — SMALL warehouse';

ALTER WAREHOUSE FINSERV_WH_SMALL RESUME IF SUSPENDED;

USE WAREHOUSE FINSERV_WH_SMALL;
SELECT COUNT(*) AS ROW_COUNT,
       SUM(AMOUNT) AS TOTAL,
       AVG(AMOUNT) AS AVG_AMT
FROM BASE.TRANSACTIONS t
JOIN BASE.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
JOIN BASE.CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID;

USE WAREHOUSE FINSERV_WH;
SELECT COUNT(*) AS ROW_COUNT,
       SUM(AMOUNT) AS TOTAL,
       AVG(AMOUNT) AS AVG_AMT
FROM BASE.TRANSACTIONS t
JOIN BASE.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
JOIN BASE.CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID;

SELECT
    QUERY_ID, WAREHOUSE_NAME, WAREHOUSE_SIZE,
    EXECUTION_TIME, COMPILATION_TIME,
    BYTES_SCANNED, ROWS_PRODUCED,
    PARTITIONS_SCANNED, PARTITIONS_TOTAL,
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME IN ('FINSERV_WH', 'FINSERV_WH_SMALL')
  AND START_TIME >= DATEADD('minute', -10, CURRENT_TIMESTAMP())
  AND QUERY_TYPE = 'SELECT'
ORDER BY START_TIME DESC
LIMIT 10;

ALTER WAREHOUSE FINSERV_WH_SMALL SUSPEND;


-- ============================================================
-- 3. MICRO-PARTITIONS & CLUSTERING METADATA
--    Inspect how data is physically organized.
-- ============================================================

SELECT SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS', '(ACCOUNT_ID)') AS CLUSTERING_INFO;

SELECT SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS', '(TXN_DATE)') AS CLUSTERING_INFO;

SELECT SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS', '(CATEGORY)') AS CLUSTERING_INFO;

SELECT
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    ROUND(BYTES / POWER(1024, 2), 2) AS SIZE_MB,
    CLUSTERING_KEY
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'BASE'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY BYTES DESC;


-- ============================================================
-- 4. AUTOMATIC CLUSTERING
--    Add clustering keys and monitor auto-clustering.
-- ============================================================

CREATE TABLE IF NOT EXISTS BASE.TRANSACTIONS_CLUSTERED
    CLUSTER BY (CATEGORY, CHANNEL)
AS SELECT * FROM BASE.TRANSACTIONS;

SELECT SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS_CLUSTERED', '(CATEGORY, CHANNEL)') AS AFTER_CLUSTER;

SELECT * FROM TABLE(INFORMATION_SCHEMA.AUTOMATIC_CLUSTERING_HISTORY(
    DATE_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP()),
    TABLE_NAME       => 'FINSERV_DB.BASE.TRANSACTIONS_CLUSTERED'
));

SELECT
    'UNCLUSTERED' AS VERSION,
    PARSE_JSON(SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS', '(CATEGORY, CHANNEL)')):average_overlaps::FLOAT AS AVG_OVERLAP,
    PARSE_JSON(SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS', '(CATEGORY, CHANNEL)')):average_depth::FLOAT AS AVG_DEPTH
UNION ALL
SELECT
    'CLUSTERED',
    PARSE_JSON(SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS_CLUSTERED', '(CATEGORY, CHANNEL)')):average_overlaps::FLOAT,
    PARSE_JSON(SYSTEM$CLUSTERING_INFORMATION('BASE.TRANSACTIONS_CLUSTERED', '(CATEGORY, CHANNEL)')):average_depth::FLOAT;


-- ============================================================
-- 5. SEARCH OPTIMIZATION SERVICE
--    Speed up point lookups and substring searches.
-- ============================================================

ALTER TABLE BASE.SUPPORT_TICKETS ADD SEARCH OPTIMIZATION ON EQUALITY(TICKET_ID, CUSTOMER_ID);

ALTER TABLE BASE.SUPPORT_TICKETS ADD SEARCH OPTIMIZATION ON SUBSTRING(SUBJECT, BODY);

DESCRIBE SEARCH OPTIMIZATION ON BASE.SUPPORT_TICKETS;

SELECT * FROM TABLE(INFORMATION_SCHEMA.SEARCH_OPTIMIZATION_HISTORY(
    DATE_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP()),
    TABLE_NAME       => 'FINSERV_DB.BASE.SUPPORT_TICKETS'
));

EXPLAIN USING TABULAR
SELECT * FROM BASE.SUPPORT_TICKETS WHERE TICKET_ID = 500;

EXPLAIN USING TABULAR
SELECT * FROM BASE.SUPPORT_TICKETS WHERE BODY LIKE '%unauthorized%';


-- ============================================================
-- 6. RESULT CACHE & METADATA CACHE
--    Demonstrate Snowflake's multi-layer caching.
-- ============================================================

SELECT COUNT(*) AS TOTAL_TXNS FROM BASE.TRANSACTIONS;
SELECT COUNT(*) AS TOTAL_TXNS FROM BASE.TRANSACTIONS;

SELECT QUERY_ID, QUERY_TEXT, EXECUTION_STATUS,
       BYTES_SCANNED, ROWS_PRODUCED,
       EXECUTION_TIME,
       PERCENTAGE_SCANNED_FROM_CACHE
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 5,
    END_TIME_RANGE_START => DATEADD('minute', -5, CURRENT_TIMESTAMP())
))
WHERE QUERY_TEXT ILIKE '%TOTAL_TXNS%'
ORDER BY START_TIME DESC;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

SELECT COUNT(*) AS TOTAL_TXNS FROM BASE.TRANSACTIONS;

ALTER SESSION SET USE_CACHED_RESULT = TRUE;

SELECT QUERY_ID, QUERY_TEXT,
       EXECUTION_TIME,
       PERCENTAGE_SCANNED_FROM_CACHE
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 5,
    END_TIME_RANGE_START => DATEADD('minute', -5, CURRENT_TIMESTAMP())
))
WHERE QUERY_TEXT ILIKE '%TOTAL_TXNS%'
ORDER BY START_TIME DESC;


-- ============================================================
-- 7. WAREHOUSE UTILIZATION & SPILLING
--    Monitor load, queuing, and disk spill.
-- ============================================================

SELECT *
FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_LOAD_HISTORY(
    DATE_RANGE_START => DATEADD('hour', -2, CURRENT_TIMESTAMP()),
    WAREHOUSE_NAME   => 'FINSERV_WH'
))
ORDER BY START_TIME DESC
LIMIT 20;

SELECT
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    AVG(EXECUTION_TIME) AS AVG_EXEC_MS,
    AVG(QUEUED_OVERLOAD_TIME) AS AVG_QUEUE_MS,
    SUM(BYTES_SPILLED_TO_LOCAL_STORAGE) AS TOTAL_LOCAL_SPILL,
    SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS TOTAL_REMOTE_SPILL,
    AVG(PARTITIONS_SCANNED) AS AVG_PARTITIONS_SCANNED,
    AVG(PARTITIONS_TOTAL) AS AVG_PARTITIONS_TOTAL,
    ROUND(AVG(PARTITIONS_SCANNED) / NULLIF(AVG(PARTITIONS_TOTAL), 0) * 100, 2) AS PARTITION_SCAN_PCT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME = 'FINSERV_WH'
  AND START_TIME >= DATEADD('hour', -2, CURRENT_TIMESTAMP())
  AND QUERY_TYPE = 'SELECT'
GROUP BY WAREHOUSE_NAME;


-- ============================================================
-- 8. QUERY ACCELERATION SERVICE
--    Offload portions of large scans to shared compute.
-- ============================================================

SELECT SYSTEM$ESTIMATE_QUERY_ACCELERATION('FINSERV_WH') AS QAS_ESTIMATE;

SELECT
    QUERY_ID, ELIGIBLE_QUERY_ACCELERATION_TIME, UPPER_LIMIT_SCALE_FACTOR
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE
WHERE WAREHOUSE_NAME = 'FINSERV_WH'
  AND START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
ORDER BY ELIGIBLE_QUERY_ACCELERATION_TIME DESC
LIMIT 10;


-- ============================================================
-- 9. RESOURCE MONITORS
--    Set credit guardrails on warehouses.
-- ============================================================

CREATE OR REPLACE RESOURCE MONITOR FINSERV_MONITOR
    WITH CREDIT_QUOTA = 10
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 95 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE FINSERV_WH SET RESOURCE_MONITOR = FINSERV_MONITOR;

SHOW RESOURCE MONITORS;


-- ============================================================
-- 10. PERFORMANCE SUMMARY TABLE
--     Capture key metrics for comparison.
-- ============================================================

CREATE OR REPLACE TABLE CONSUMPTION.PERFORMANCE_SUMMARY AS
SELECT
    QUERY_ID,
    QUERY_TEXT,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    EXECUTION_TIME AS EXEC_MS,
    COMPILATION_TIME AS COMPILE_MS,
    BYTES_SCANNED,
    ROWS_PRODUCED,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) * 100, 2) AS PARTITION_SCAN_PCT,
    BYTES_SPILLED_TO_LOCAL_STORAGE AS LOCAL_SPILL,
    BYTES_SPILLED_TO_REMOTE_STORAGE AS REMOTE_SPILL,
    PERCENTAGE_SCANNED_FROM_CACHE AS CACHE_HIT_PCT,
    QUEUED_OVERLOAD_TIME AS QUEUE_MS,
    START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME IN ('FINSERV_WH', 'FINSERV_WH_SMALL')
  AND START_TIME >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
  AND QUERY_TYPE = 'SELECT'
ORDER BY START_TIME DESC;

SELECT * FROM CONSUMPTION.PERFORMANCE_SUMMARY
ORDER BY START_TIME DESC
LIMIT 20;

SELECT '>>> PERFORMANCE EXPLORATION COMPLETE <<<' AS STATUS;
