/*=============================================================================
  FINSERV DEMO — Step 21: Security & Access Control
  End-to-end security implementation: RBAC, network policies, session policies,
  dynamic data masking, and row access policies.
  Run this after scripts 01-08 are deployed and validated.
=============================================================================*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINSERV_WH;
USE DATABASE FINSERV_DB;


-- ============================================================
-- 1. CUSTOM ROLES & RBAC HIERARCHY
--    Functional roles (job personas) + Access roles (permissions).
--    Pattern: Access Roles → Functional Roles → SYSADMIN
-- ============================================================

SELECT '>>> CREATING RBAC HIERARCHY <<<' AS SECTION;

-- Access roles (define what permissions exist)
CREATE ROLE IF NOT EXISTS FINSERV_BASE_READ
    COMMENT = 'Read-only access to BASE schema tables';
CREATE ROLE IF NOT EXISTS FINSERV_CURATED_READ
    COMMENT = 'Read-only access to CURATED schema dynamic tables';
CREATE ROLE IF NOT EXISTS FINSERV_CONSUMPTION_READ
    COMMENT = 'Read-only access to CONSUMPTION schema analytics';
CREATE ROLE IF NOT EXISTS FINSERV_RAW_WRITE
    COMMENT = 'Read-write access to RAW schema event tables';

-- Functional roles (define who uses them)
CREATE ROLE IF NOT EXISTS FINSERV_ADMIN
    COMMENT = 'Full access to all FINSERV objects — data platform owner';
CREATE ROLE IF NOT EXISTS FINSERV_ANALYST
    COMMENT = 'Business analyst — reads curated + consumption data';
CREATE ROLE IF NOT EXISTS FINSERV_DATA_ENGINEER
    COMMENT = 'Pipeline builder — reads base, writes raw, reads curated';
CREATE ROLE IF NOT EXISTS FINSERV_COMPLIANCE_OFFICER
    COMMENT = 'Compliance/audit — full read access including PII';
CREATE ROLE IF NOT EXISTS FINSERV_SUPPORT_AGENT
    COMMENT = 'Customer support — limited to assigned tickets only';

-- Wire access roles → functional roles
GRANT ROLE FINSERV_BASE_READ        TO ROLE FINSERV_ADMIN;
GRANT ROLE FINSERV_CURATED_READ     TO ROLE FINSERV_ADMIN;
GRANT ROLE FINSERV_CONSUMPTION_READ TO ROLE FINSERV_ADMIN;
GRANT ROLE FINSERV_RAW_WRITE        TO ROLE FINSERV_ADMIN;

GRANT ROLE FINSERV_CURATED_READ     TO ROLE FINSERV_ANALYST;
GRANT ROLE FINSERV_CONSUMPTION_READ TO ROLE FINSERV_ANALYST;

GRANT ROLE FINSERV_BASE_READ        TO ROLE FINSERV_DATA_ENGINEER;
GRANT ROLE FINSERV_CURATED_READ     TO ROLE FINSERV_DATA_ENGINEER;
GRANT ROLE FINSERV_RAW_WRITE        TO ROLE FINSERV_DATA_ENGINEER;

GRANT ROLE FINSERV_BASE_READ        TO ROLE FINSERV_COMPLIANCE_OFFICER;
GRANT ROLE FINSERV_CURATED_READ     TO ROLE FINSERV_COMPLIANCE_OFFICER;
GRANT ROLE FINSERV_CONSUMPTION_READ TO ROLE FINSERV_COMPLIANCE_OFFICER;

GRANT ROLE FINSERV_CONSUMPTION_READ TO ROLE FINSERV_SUPPORT_AGENT;

-- Functional roles → SYSADMIN (maintains hierarchy)
GRANT ROLE FINSERV_ADMIN              TO ROLE SYSADMIN;
GRANT ROLE FINSERV_ANALYST            TO ROLE SYSADMIN;
GRANT ROLE FINSERV_DATA_ENGINEER      TO ROLE SYSADMIN;
GRANT ROLE FINSERV_COMPLIANCE_OFFICER TO ROLE SYSADMIN;
GRANT ROLE FINSERV_SUPPORT_AGENT      TO ROLE SYSADMIN;

-- Verify
SHOW ROLES LIKE 'FINSERV%';


-- ============================================================
-- 2. GRANT PRIVILEGES TO ACCESS ROLES
--    Least-privilege grants per schema with future grants.
-- ============================================================

SELECT '>>> GRANTING PRIVILEGES <<<' AS SECTION;

-- Warehouse usage for all functional roles
GRANT USAGE ON WAREHOUSE FINSERV_WH TO ROLE FINSERV_ADMIN;
GRANT USAGE ON WAREHOUSE FINSERV_WH TO ROLE FINSERV_ANALYST;
GRANT USAGE ON WAREHOUSE FINSERV_WH TO ROLE FINSERV_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE FINSERV_WH TO ROLE FINSERV_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE FINSERV_WH TO ROLE FINSERV_SUPPORT_AGENT;

-- Database usage for all access roles
GRANT USAGE ON DATABASE FINSERV_DB TO ROLE FINSERV_BASE_READ;
GRANT USAGE ON DATABASE FINSERV_DB TO ROLE FINSERV_CURATED_READ;
GRANT USAGE ON DATABASE FINSERV_DB TO ROLE FINSERV_CONSUMPTION_READ;
GRANT USAGE ON DATABASE FINSERV_DB TO ROLE FINSERV_RAW_WRITE;

-- FINSERV_BASE_READ: SELECT on BASE
GRANT USAGE ON SCHEMA BASE TO ROLE FINSERV_BASE_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA BASE TO ROLE FINSERV_BASE_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BASE TO ROLE FINSERV_BASE_READ;

-- FINSERV_CURATED_READ: SELECT on CURATED
GRANT USAGE ON SCHEMA CURATED TO ROLE FINSERV_CURATED_READ;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED TO ROLE FINSERV_CURATED_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE FINSERV_CURATED_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE FINSERV_CURATED_READ;

-- FINSERV_CONSUMPTION_READ: SELECT on CONSUMPTION
GRANT USAGE ON SCHEMA CONSUMPTION TO ROLE FINSERV_CONSUMPTION_READ;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONSUMPTION TO ROLE FINSERV_CONSUMPTION_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA CONSUMPTION TO ROLE FINSERV_CONSUMPTION_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONSUMPTION TO ROLE FINSERV_CONSUMPTION_READ;

-- FINSERV_RAW_WRITE: Read + write on RAW event tables
GRANT USAGE ON SCHEMA RAW TO ROLE FINSERV_RAW_WRITE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE FINSERV_RAW_WRITE;
GRANT INSERT, UPDATE ON TABLE RAW.TRANSACTION_ALERTS TO ROLE FINSERV_RAW_WRITE;
GRANT INSERT, UPDATE ON TABLE RAW.TICKET_ESCALATIONS TO ROLE FINSERV_RAW_WRITE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE FINSERV_RAW_WRITE;

-- Also grant RAW read to compliance (for audit)
GRANT USAGE ON SCHEMA RAW TO ROLE FINSERV_COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE FINSERV_COMPLIANCE_OFFICER;


-- ============================================================
-- 3. NETWORK POLICY
--    Restrict access to trusted IP ranges.
-- ============================================================

SELECT '>>> NETWORK POLICY <<<' AS SECTION;

-- Example: allow corporate office + VPN ranges
-- Replace with your actual IP ranges before applying to account
CREATE OR REPLACE NETWORK POLICY FINSERV_NETWORK_POLICY
    ALLOWED_IP_LIST = ('203.0.113.0/24', '198.51.100.0/24', '10.0.0.0/8')
    BLOCKED_IP_LIST = ()
    COMMENT = 'FINSERV demo — restrict to corporate + VPN IPs';

-- View the policy (do NOT apply to account in demo — would lock out!)
SHOW NETWORK POLICIES;
DESCRIBE NETWORK POLICY FINSERV_NETWORK_POLICY;

-- To apply (uncomment when ready with real IPs):
-- ALTER ACCOUNT SET NETWORK_POLICY = FINSERV_NETWORK_POLICY;
-- To apply per-user instead:
-- ALTER USER demo_analyst SET NETWORK_POLICY = FINSERV_NETWORK_POLICY;


-- ============================================================
-- 4. SESSION POLICY
--    Idle timeout and max session duration for security.
-- ============================================================

SELECT '>>> SESSION POLICY <<<' AS SECTION;

CREATE OR REPLACE SESSION POLICY FINSERV_DB.RAW.FINSERV_SESSION_POLICY
    SESSION_IDLE_TIMEOUT_MINS       = 30
    SESSION_UI_IDLE_TIMEOUT_MINS    = 15
    COMMENT = 'FINSERV — auto-disconnect idle sessions for security';

-- To apply (uncomment when ready):
-- ALTER ACCOUNT SET SESSION POLICY FINSERV_DB.RAW.FINSERV_SESSION_POLICY;
-- Or per-user:
-- ALTER USER demo_analyst SET SESSION POLICY FINSERV_DB.RAW.FINSERV_SESSION_POLICY;

SHOW SESSION POLICIES IN SCHEMA RAW;


-- ============================================================
-- 5. DYNAMIC DATA MASKING — PII COLUMNS
--    Mask names, email, phone, DOB, income, credit score.
--    Only FINSERV_ADMIN and FINSERV_COMPLIANCE_OFFICER see real data.
-- ============================================================

SELECT '>>> PII MASKING POLICIES <<<' AS SECTION;

-- Masking policy: VARCHAR (names, email, phone)
CREATE OR REPLACE MASKING POLICY BASE.MASK_PII_STRING AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE '***MASKED***'
    END;

-- Masking policy: DATE (date of birth)
CREATE OR REPLACE MASKING POLICY BASE.MASK_PII_DATE AS (val DATE)
RETURNS DATE ->
    CASE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)  -- Redact to Jan 1 of birth year
    END;

-- Masking policy: NUMBER — income/credit score
CREATE OR REPLACE MASKING POLICY BASE.MASK_PII_NUMBER AS (val NUMBER(12,2))
RETURNS NUMBER(12,2) ->
    CASE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE -1  -- Sentinel value indicating masked
    END;

-- Masking policy: NUMBER(4,0) — credit score specifically
CREATE OR REPLACE MASKING POLICY BASE.MASK_CREDIT_SCORE AS (val NUMBER(4,0))
RETURNS NUMBER(4,0) ->
    CASE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE 0
    END;

-- Apply PII masking to CUSTOMERS table
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN FIRST_NAME    SET MASKING POLICY BASE.MASK_PII_STRING;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN LAST_NAME     SET MASKING POLICY BASE.MASK_PII_STRING;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN EMAIL         SET MASKING POLICY BASE.MASK_PII_STRING;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN PHONE         SET MASKING POLICY BASE.MASK_PII_STRING;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY BASE.MASK_PII_DATE;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN ANNUAL_INCOME SET MASKING POLICY BASE.MASK_PII_NUMBER;
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN CREDIT_SCORE  SET MASKING POLICY BASE.MASK_CREDIT_SCORE;

SELECT 'Applied 7 masking policies to CUSTOMERS PII columns' AS STATUS;


-- ============================================================
-- 6. DYNAMIC DATA MASKING — FINANCIAL COLUMNS
--    Mask BALANCE and CREDIT_LIMIT in ACCOUNTS.
--    Visible to FINSERV_ADMIN and FINSERV_ANALYST.
-- ============================================================

SELECT '>>> FINANCIAL MASKING POLICIES <<<' AS SECTION;

CREATE OR REPLACE MASKING POLICY BASE.MASK_FINANCIAL_AMOUNT AS (val NUMBER(15,2))
RETURNS NUMBER(15,2) ->
    CASE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_ANALYST') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE -1.00
    END;

ALTER TABLE BASE.ACCOUNTS MODIFY COLUMN BALANCE      SET MASKING POLICY BASE.MASK_FINANCIAL_AMOUNT;
ALTER TABLE BASE.ACCOUNTS MODIFY COLUMN CREDIT_LIMIT SET MASKING POLICY BASE.MASK_FINANCIAL_AMOUNT;

SELECT 'Applied 2 masking policies to ACCOUNTS financial columns' AS STATUS;


-- ============================================================
-- 7. ROW ACCESS POLICY — SUPPORT TICKETS
--    Support agents see only tickets assigned to them.
--    Compliance and Admin see all rows.
-- ============================================================

SELECT '>>> ROW ACCESS POLICY: SUPPORT TICKETS <<<' AS SECTION;

-- Mapping table: which user handles which agent name
CREATE TABLE IF NOT EXISTS RAW.SUPPORT_AGENT_MAP (
    SNOWFLAKE_USER  VARCHAR(100) NOT NULL,
    AGENT_NAME      VARCHAR(50)  NOT NULL,
    CONSTRAINT PK_AGENT_MAP PRIMARY KEY (SNOWFLAKE_USER)
);

-- Seed with sample mappings (replace with real users)
INSERT INTO RAW.SUPPORT_AGENT_MAP (SNOWFLAKE_USER, AGENT_NAME)
SELECT 'DEMO_SUPPORT_1', 'Fraud Team'
WHERE NOT EXISTS (SELECT 1 FROM RAW.SUPPORT_AGENT_MAP WHERE SNOWFLAKE_USER = 'DEMO_SUPPORT_1');
INSERT INTO RAW.SUPPORT_AGENT_MAP (SNOWFLAKE_USER, AGENT_NAME)
SELECT 'DEMO_SUPPORT_2', 'Card Services'
WHERE NOT EXISTS (SELECT 1 FROM RAW.SUPPORT_AGENT_MAP WHERE SNOWFLAKE_USER = 'DEMO_SUPPORT_2');

-- Row access policy
CREATE OR REPLACE ROW ACCESS POLICY BASE.RAP_SUPPORT_TICKETS
    AS (assigned_to VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_SUPPORT_AGENT')
            THEN EXISTS (
                SELECT 1 FROM RAW.SUPPORT_AGENT_MAP
                WHERE SNOWFLAKE_USER = CURRENT_USER()
                  AND AGENT_NAME = assigned_to
            )
        ELSE FALSE
    END;

ALTER TABLE BASE.SUPPORT_TICKETS
    ADD ROW ACCESS POLICY BASE.RAP_SUPPORT_TICKETS ON (ASSIGNED_TO);

SELECT 'Applied row access policy to SUPPORT_TICKETS' AS STATUS;


-- ============================================================
-- 8. ROW ACCESS POLICY — COUNTRY-BASED CUSTOMER ACCESS
--    Analysts see only customers in their assigned countries.
-- ============================================================

SELECT '>>> ROW ACCESS POLICY: COUNTRY-BASED <<<' AS SECTION;

-- Mapping table: which user sees which countries
CREATE TABLE IF NOT EXISTS RAW.ANALYST_COUNTRY_MAP (
    SNOWFLAKE_USER  VARCHAR(100) NOT NULL,
    COUNTRY         VARCHAR(50)  NOT NULL
);

-- Seed with sample mappings
INSERT INTO RAW.ANALYST_COUNTRY_MAP (SNOWFLAKE_USER, COUNTRY)
SELECT column1, column2 FROM VALUES
    ('DEMO_ANALYST_US', 'United States'),
    ('DEMO_ANALYST_US', 'Canada'),
    ('DEMO_ANALYST_EU', 'United Kingdom'),
    ('DEMO_ANALYST_EU', 'Germany'),
    ('DEMO_ANALYST_EU', 'France'),
    ('DEMO_ANALYST_APAC', 'Japan'),
    ('DEMO_ANALYST_APAC', 'Australia'),
    ('DEMO_ANALYST_APAC', 'India')
WHERE NOT EXISTS (SELECT 1 FROM RAW.ANALYST_COUNTRY_MAP LIMIT 1);

-- Row access policy
CREATE OR REPLACE ROW ACCESS POLICY BASE.RAP_CUSTOMER_COUNTRY
    AS (country VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ANALYST')
            THEN EXISTS (
                SELECT 1 FROM RAW.ANALYST_COUNTRY_MAP
                WHERE SNOWFLAKE_USER = CURRENT_USER()
                  AND COUNTRY = country
            )
        ELSE TRUE  -- Other roles with table access see all rows
    END;

ALTER TABLE BASE.CUSTOMERS
    ADD ROW ACCESS POLICY BASE.RAP_CUSTOMER_COUNTRY ON (COUNTRY);

SELECT 'Applied country-based row access policy to CUSTOMERS' AS STATUS;


-- ============================================================
-- 9. VERIFY SECURITY CONTROLS
--    Test masking and row access under different roles.
-- ============================================================

SELECT '>>> SECURITY VERIFICATION <<<' AS SECTION;

-- As ACCOUNTADMIN: should see all real data
SELECT 'ACCOUNTADMIN view' AS ROLE_TEST,
       CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE,
       DATE_OF_BIRTH, ANNUAL_INCOME, CREDIT_SCORE, COUNTRY
FROM BASE.CUSTOMERS
ORDER BY CUSTOMER_ID
LIMIT 5;

-- Switch to FINSERV_ANALYST and test masking
-- (Uncomment after granting FINSERV_ANALYST to your user)
-- USE ROLE FINSERV_ANALYST;
-- SELECT 'FINSERV_ANALYST view (PII masked)' AS ROLE_TEST,
--        CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE,
--        DATE_OF_BIRTH, ANNUAL_INCOME, CREDIT_SCORE, COUNTRY
-- FROM BASE.CUSTOMERS
-- ORDER BY CUSTOMER_ID
-- LIMIT 5;
-- USE ROLE ACCOUNTADMIN;

-- Verify policies are attached
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, POLICY_NAME
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_DOMAIN => 'TABLE',
    REF_ENTITY_NAME   => 'FINSERV_DB.BASE.CUSTOMERS'
));

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, POLICY_NAME
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_DOMAIN => 'TABLE',
    REF_ENTITY_NAME   => 'FINSERV_DB.BASE.ACCOUNTS'
));

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, POLICY_NAME
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_DOMAIN => 'TABLE',
    REF_ENTITY_NAME   => 'FINSERV_DB.BASE.SUPPORT_TICKETS'
));


-- ============================================================
-- 10. SECURITY AUDIT SUMMARY
--     Query account usage for a security posture snapshot.
-- ============================================================

SELECT '>>> SECURITY AUDIT SUMMARY <<<' AS SECTION;

-- All custom roles and their grants
SELECT GRANTEE_NAME AS ROLE_NAME, GRANTED_ON, NAME AS GRANTED_OBJECT, PRIVILEGE
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE GRANTEE_NAME LIKE 'FINSERV%'
  AND DELETED_ON IS NULL
ORDER BY GRANTEE_NAME, GRANTED_ON, NAME;

-- All masking policies in FINSERV_DB
SELECT POLICY_NAME, POLICY_KIND, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
WHERE REF_DATABASE_NAME = 'FINSERV_DB'
  AND POLICY_KIND IN ('MASKING_POLICY', 'ROW_ACCESS_POLICY')
ORDER BY POLICY_KIND, REF_ENTITY_NAME;

-- Recent login history (last 24h)
SELECT USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE,
       FIRST_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_MESSAGE,
       EVENT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC
LIMIT 20;

-- Failed login attempts (security monitoring)
SELECT USER_NAME, CLIENT_IP, ERROR_CODE, ERROR_MESSAGE,
       COUNT(*) AS FAILURE_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
  AND EVENT_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY USER_NAME, CLIENT_IP, ERROR_CODE, ERROR_MESSAGE
ORDER BY FAILURE_COUNT DESC;

SELECT '>>> SECURITY MODULE COMPLETE <<<' AS STATUS;
