/*=============================================================================
  FINSERV DEMO — Step 22: Data Governance End-to-End
  Classification, tagging, tag-based masking, aggregation policies,
  projection policies, data metric functions, and access auditing.
  Run this after script 21 (security) is deployed.
=============================================================================*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINSERV_WH;
USE DATABASE FINSERV_DB;


-- ============================================================
-- 1. GOVERNANCE SCHEMA & TAGS
--    Central schema for governance objects + classification tags.
-- ============================================================

SELECT '>>> GOVERNANCE SETUP <<<' AS SECTION;

CREATE SCHEMA IF NOT EXISTS GOVERNANCE
    COMMENT = 'Data governance — tags, policies, classification profiles';

-- Tag: Data sensitivity classification
CREATE OR REPLACE TAG GOVERNANCE.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PII', 'RESTRICTED', 'SENSITIVE', 'INTERNAL', 'PUBLIC'
    COMMENT = 'Data sensitivity level for columns and tables';

-- Tag: Data owner (responsible team)
CREATE OR REPLACE TAG GOVERNANCE.DATA_OWNER
    ALLOWED_VALUES 'PLATFORM_TEAM', 'ANALYTICS_TEAM', 'COMPLIANCE_TEAM',
                   'SUPPORT_TEAM', 'RISK_TEAM', 'MARKET_DATA_TEAM'
    COMMENT = 'Team responsible for data stewardship';

-- Tag: Regulatory framework applicability
CREATE OR REPLACE TAG GOVERNANCE.REGULATORY_FRAMEWORK
    ALLOWED_VALUES 'GDPR', 'CCPA', 'PCI_DSS', 'SOX', 'BSA_AML', 'NONE'
    COMMENT = 'Applicable regulatory compliance framework';

-- Tag: Data retention policy
CREATE OR REPLACE TAG GOVERNANCE.RETENTION_POLICY
    ALLOWED_VALUES '30_DAYS', '90_DAYS', '1_YEAR', '3_YEARS', '7_YEARS', 'INDEFINITE'
    COMMENT = 'Data retention requirement';

SHOW TAGS IN SCHEMA GOVERNANCE;


-- ============================================================
-- 2. MANUAL TAG ASSIGNMENT
--    Classify columns and tables with governance tags.
-- ============================================================

SELECT '>>> TAGGING OBJECTS <<<' AS SECTION;

-- CUSTOMERS: PII columns
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN FIRST_NAME
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN LAST_NAME
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN EMAIL
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN PHONE
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'RESTRICTED';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN ANNUAL_INCOME
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN CREDIT_SCORE
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN CITY
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN STATE
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL';
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN COUNTRY
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL';

-- ACCOUNTS: financial columns
ALTER TABLE BASE.ACCOUNTS MODIFY COLUMN BALANCE
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';
ALTER TABLE BASE.ACCOUNTS MODIFY COLUMN CREDIT_LIMIT
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';
ALTER TABLE BASE.ACCOUNTS MODIFY COLUMN INTEREST_RATE
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL';

-- TRANSACTIONS: flagged indicator
ALTER TABLE BASE.TRANSACTIONS MODIFY COLUMN IS_FLAGGED
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'RESTRICTED';
ALTER TABLE BASE.TRANSACTIONS MODIFY COLUMN AMOUNT
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';

-- SUPPORT_TICKETS: free text may contain PII
ALTER TABLE BASE.SUPPORT_TICKETS MODIFY COLUMN BODY
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE BASE.SUPPORT_TICKETS MODIFY COLUMN SUBJECT
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL';

-- RISK_ASSESSMENTS: VARIANT contains risk scores
ALTER TABLE BASE.RISK_ASSESSMENTS MODIFY COLUMN RISK_DATA
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE';

-- COMPLIANCE_DOCUMENTS: regulatory content
ALTER TABLE BASE.COMPLIANCE_DOCUMENTS MODIFY COLUMN DOC_CONTENT
    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'RESTRICTED';

-- Table-level tags: data ownership
ALTER TABLE BASE.CUSTOMERS            SET TAG GOVERNANCE.DATA_OWNER = 'PLATFORM_TEAM';
ALTER TABLE BASE.ACCOUNTS             SET TAG GOVERNANCE.DATA_OWNER = 'PLATFORM_TEAM';
ALTER TABLE BASE.TRANSACTIONS         SET TAG GOVERNANCE.DATA_OWNER = 'ANALYTICS_TEAM';
ALTER TABLE BASE.RISK_ASSESSMENTS     SET TAG GOVERNANCE.DATA_OWNER = 'RISK_TEAM';
ALTER TABLE BASE.MARKET_DATA          SET TAG GOVERNANCE.DATA_OWNER = 'MARKET_DATA_TEAM';
ALTER TABLE BASE.SUPPORT_TICKETS      SET TAG GOVERNANCE.DATA_OWNER = 'SUPPORT_TEAM';
ALTER TABLE BASE.COMPLIANCE_DOCUMENTS SET TAG GOVERNANCE.DATA_OWNER = 'COMPLIANCE_TEAM';

-- Table-level tags: regulatory framework
ALTER TABLE BASE.CUSTOMERS            SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'GDPR';
ALTER TABLE BASE.ACCOUNTS             SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'SOX';
ALTER TABLE BASE.TRANSACTIONS         SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'PCI_DSS';
ALTER TABLE BASE.RISK_ASSESSMENTS     SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'BSA_AML';
ALTER TABLE BASE.SUPPORT_TICKETS      SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'CCPA';
ALTER TABLE BASE.COMPLIANCE_DOCUMENTS SET TAG GOVERNANCE.REGULATORY_FRAMEWORK = 'SOX';

-- Table-level tags: retention
ALTER TABLE BASE.TRANSACTIONS         SET TAG GOVERNANCE.RETENTION_POLICY = '7_YEARS';
ALTER TABLE BASE.CUSTOMERS            SET TAG GOVERNANCE.RETENTION_POLICY = '3_YEARS';
ALTER TABLE BASE.COMPLIANCE_DOCUMENTS SET TAG GOVERNANCE.RETENTION_POLICY = '7_YEARS';
ALTER TABLE BASE.SUPPORT_TICKETS      SET TAG GOVERNANCE.RETENTION_POLICY = '1_YEAR';

SELECT 'Tagged all BASE tables and sensitive columns' AS STATUS;


-- ============================================================
-- 3. AUTOMATED CLASSIFICATION
--    Use SYSTEM$CLASSIFY to auto-detect PII in tables.
-- ============================================================

SELECT '>>> AUTOMATED CLASSIFICATION <<<' AS SECTION;

-- Classify CUSTOMERS table — should detect EMAIL, PHONE, DOB, etc.
SELECT SYSTEM$CLASSIFY('FINSERV_DB.BASE.CUSTOMERS', {'auto_tag': true});

-- Classify SUPPORT_TICKETS — may detect PII in free-text BODY
SELECT SYSTEM$CLASSIFY('FINSERV_DB.BASE.SUPPORT_TICKETS', {'auto_tag': true});

-- Classify ACCOUNTS
SELECT SYSTEM$CLASSIFY('FINSERV_DB.BASE.ACCOUNTS', {'auto_tag': true});

-- View auto-classification results
SELECT *
FROM TABLE(
    FINSERV_DB.INFORMATION_SCHEMA.TAG_REFERENCES(
        'FINSERV_DB.BASE.CUSTOMERS', 'TABLE'
    )
)
ORDER BY COLUMN_NAME;

-- Compare: which columns have both manual and auto tags
SELECT
    TAG_NAME,
    COLUMN_NAME,
    TAG_VALUE,
    DOMAIN
FROM TABLE(
    FINSERV_DB.INFORMATION_SCHEMA.TAG_REFERENCES(
        'FINSERV_DB.BASE.CUSTOMERS', 'TABLE'
    )
)
WHERE TAG_NAME LIKE '%CLASSIFICATION%' OR TAG_NAME LIKE '%PRIVACY%'
ORDER BY COLUMN_NAME, TAG_NAME;


-- ============================================================
-- 4. TAG-BASED MASKING POLICIES
--    Attach masking to the DATA_CLASSIFICATION tag so any
--    future column tagged PII/RESTRICTED is auto-protected.
-- ============================================================

SELECT '>>> TAG-BASED MASKING <<<' AS SECTION;

-- Tag-based masking: VARCHAR columns tagged with DATA_CLASSIFICATION
CREATE OR REPLACE MASKING POLICY GOVERNANCE.TAG_MASK_STRING
    AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') = 'PUBLIC' THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') = 'INTERNAL' THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') IN ('PII', 'RESTRICTED')
            THEN '***MASKED***'
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') = 'SENSITIVE'
            THEN LEFT(val, 1) || '***'
        ELSE val
    END;

-- Tag-based masking: NUMBER columns
CREATE OR REPLACE MASKING POLICY GOVERNANCE.TAG_MASK_NUMBER
    AS (val NUMBER) RETURNS NUMBER ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') IN ('PUBLIC', 'INTERNAL') THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') IN ('PII', 'RESTRICTED', 'SENSITIVE')
            THEN -1
        ELSE val
    END;

-- Tag-based masking: DATE columns
CREATE OR REPLACE MASKING POLICY GOVERNANCE.TAG_MASK_DATE
    AS (val DATE) RETURNS DATE ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') IN ('PII', 'RESTRICTED')
            THEN DATE_FROM_PARTS(YEAR(val), 1, 1)
        ELSE val
    END;

-- Tag-based masking: VARIANT columns
CREATE OR REPLACE MASKING POLICY GOVERNANCE.TAG_MASK_VARIANT
    AS (val VARIANT) RETURNS VARIANT ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN val
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN val
        WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('GOVERNANCE.DATA_CLASSIFICATION') IN ('PII', 'RESTRICTED', 'SENSITIVE')
            THEN PARSE_JSON('{"masked": true}')
        ELSE val
    END;

-- Attach masking policies to the DATA_CLASSIFICATION tag
-- NOTE: Tag-based masking and column-level masking are mutually exclusive.
-- The column-level policies from file 21 take precedence on those columns.
-- Tag-based policies protect NEW columns tagged in the future automatically.
ALTER TAG GOVERNANCE.DATA_CLASSIFICATION SET
    MASKING POLICY GOVERNANCE.TAG_MASK_STRING,
    MASKING POLICY GOVERNANCE.TAG_MASK_NUMBER,
    MASKING POLICY GOVERNANCE.TAG_MASK_DATE,
    MASKING POLICY GOVERNANCE.TAG_MASK_VARIANT;

SELECT 'Tag-based masking policies attached to DATA_CLASSIFICATION tag' AS STATUS;


-- ============================================================
-- 5. TAG-BASED ROW ACCESS POLICY
--    Row-level filtering for tables tagged RESTRICTED.
-- ============================================================

SELECT '>>> TAG-BASED ROW ACCESS <<<' AS SECTION;

-- Note: Tag-based row access policies apply at the table level when the
-- DATA_CLASSIFICATION tag is set on the table itself.
-- Tables already have column-level RAPs from file 21, so this section
-- demonstrates the pattern for future tables.

CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE.TAG_RAP_RESTRICTED
    AS (col1 VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN TRUE
        ELSE TRUE  -- Default allow; override per-table as needed
    END;

SELECT 'Tag-based row access policy created for RESTRICTED data' AS STATUS;


-- ============================================================
-- 6. AGGREGATION POLICY
--    Prevent individual-level data extraction by analysts.
--    Non-admin roles must GROUP BY with MIN_GROUP_SIZE >= 5.
-- ============================================================

SELECT '>>> AGGREGATION POLICY <<<' AS SECTION;

CREATE OR REPLACE AGGREGATION POLICY GOVERNANCE.FINSERV_AGGREGATION_POLICY
    AS () RETURNS AGGREGATION_CONSTRAINT ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN NO_AGGREGATION_CONSTRAINT()
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN NO_AGGREGATION_CONSTRAINT()
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN NO_AGGREGATION_CONSTRAINT()
        ELSE AGGREGATION_CONSTRAINT(MIN_GROUP_SIZE => 5)
    END;

-- Apply to CUSTOMERS — analysts must aggregate, no single-row extraction
ALTER TABLE BASE.CUSTOMERS
    SET AGGREGATION POLICY GOVERNANCE.FINSERV_AGGREGATION_POLICY;

SELECT 'Aggregation policy applied to CUSTOMERS (min group size = 5)' AS STATUS;

-- Test: this should work for FINSERV_ANALYST (aggregated query)
-- USE ROLE FINSERV_ANALYST;
-- SELECT COUNTRY, COUNT(*) AS CUSTOMER_COUNT, AVG(ANNUAL_INCOME) AS AVG_INCOME
-- FROM BASE.CUSTOMERS
-- GROUP BY COUNTRY;
-- USE ROLE ACCOUNTADMIN;


-- ============================================================
-- 7. PROJECTION POLICY
--    PII columns can be used in WHERE but not in SELECT output.
-- ============================================================

SELECT '>>> PROJECTION POLICY <<<' AS SECTION;

CREATE OR REPLACE PROJECTION POLICY GOVERNANCE.FINSERV_PROJECTION_POLICY
    AS () RETURNS PROJECTION_CONSTRAINT ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN PROJECTION_CONSTRAINT(ALLOW => TRUE)
        WHEN IS_ROLE_IN_SESSION('FINSERV_ADMIN') THEN PROJECTION_CONSTRAINT(ALLOW => TRUE)
        WHEN IS_ROLE_IN_SESSION('FINSERV_COMPLIANCE_OFFICER') THEN PROJECTION_CONSTRAINT(ALLOW => TRUE)
        ELSE PROJECTION_CONSTRAINT(ALLOW => FALSE)
    END;

-- Apply to EMAIL column: analysts can filter WHERE EMAIL = 'x' but not SELECT EMAIL
ALTER TABLE BASE.CUSTOMERS MODIFY COLUMN EMAIL
    SET PROJECTION POLICY GOVERNANCE.FINSERV_PROJECTION_POLICY;

SELECT 'Projection policy applied to CUSTOMERS.EMAIL' AS STATUS;

-- Test: this would fail for FINSERV_ANALYST (projecting EMAIL)
-- USE ROLE FINSERV_ANALYST;
-- SELECT EMAIL FROM BASE.CUSTOMERS LIMIT 5;  -- BLOCKED
-- SELECT COUNT(*) FROM BASE.CUSTOMERS WHERE EMAIL LIKE '%@example.com';  -- ALLOWED
-- USE ROLE ACCOUNTADMIN;


-- ============================================================
-- 8. DATA METRIC FUNCTIONS (DMFs)
--    Automated quality checks tied to governance.
-- ============================================================

SELECT '>>> DATA METRIC FUNCTIONS <<<' AS SECTION;

-- DMF: NULL rate for CUSTOMER_ID foreign key in TRANSACTIONS
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_NULL_ACCOUNT_ID(
    ARG_T TABLE(ACCOUNT_ID NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(ACCOUNT_ID IS NULL) FROM ARG_T
$$;

-- DMF: Credit score range validation (300-850)
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_CREDIT_SCORE_RANGE(
    ARG_T TABLE(CREDIT_SCORE NUMBER(4,0))
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(CREDIT_SCORE < 300 OR CREDIT_SCORE > 850) FROM ARG_T
$$;

-- DMF: Email format validation (basic @ check)
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_EMAIL_FORMAT(
    ARG_T TABLE(EMAIL VARCHAR)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(EMAIL IS NOT NULL AND EMAIL NOT LIKE '%_@_%.__%') FROM ARG_T
$$;

-- DMF: Negative balance detection
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_NEGATIVE_BALANCE(
    ARG_T TABLE(BALANCE NUMBER(15,2))
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(BALANCE < 0) FROM ARG_T
$$;

-- DMF: Future transaction date detection
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_FUTURE_TXN_DATE(
    ARG_T TABLE(TXN_DATE TIMESTAMP_NTZ)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(TXN_DATE > CURRENT_TIMESTAMP()) FROM ARG_T
$$;

-- Schedule DMFs on tables (run every 60 minutes)
ALTER TABLE BASE.TRANSACTIONS SET DATA_METRIC_SCHEDULE = '60 MINUTE';
ALTER TABLE BASE.CUSTOMERS SET DATA_METRIC_SCHEDULE = '60 MINUTE';
ALTER TABLE BASE.ACCOUNTS SET DATA_METRIC_SCHEDULE = '60 MINUTE';

-- Attach DMFs to specific columns
ALTER TABLE BASE.TRANSACTIONS
    ADD DATA METRIC FUNCTION GOVERNANCE.DMF_NULL_ACCOUNT_ID ON (ACCOUNT_ID);
ALTER TABLE BASE.TRANSACTIONS
    ADD DATA METRIC FUNCTION GOVERNANCE.DMF_FUTURE_TXN_DATE ON (TXN_DATE);
ALTER TABLE BASE.CUSTOMERS
    ADD DATA METRIC FUNCTION GOVERNANCE.DMF_CREDIT_SCORE_RANGE ON (CREDIT_SCORE);
ALTER TABLE BASE.CUSTOMERS
    ADD DATA METRIC FUNCTION GOVERNANCE.DMF_EMAIL_FORMAT ON (EMAIL);
ALTER TABLE BASE.ACCOUNTS
    ADD DATA METRIC FUNCTION GOVERNANCE.DMF_NEGATIVE_BALANCE ON (BALANCE);

SELECT 'Attached 5 DMFs to BASE tables' AS STATUS;


-- ============================================================
-- 9. ACCESS HISTORY & AUDIT QUERIES
--    Who accessed what PII, when, and from where.
-- ============================================================

SELECT '>>> ACCESS HISTORY & AUDIT <<<' AS SECTION;

-- Who accessed PII columns in the last 7 days
SELECT
    USER_NAME,
    QUERY_START_TIME,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND ARRAY_SIZE(
      ARRAY_INTERSECTION(
          TRANSFORM(BASE_OBJECTS_ACCESSED, o -> o:objectName::VARCHAR),
          ARRAY_CONSTRUCT('FINSERV_DB.BASE.CUSTOMERS')
      )
  ) > 0
ORDER BY QUERY_START_TIME DESC
LIMIT 20;

-- Tag coverage report: which columns have classification tags
SELECT
    TAG_DATABASE, TAG_SCHEMA, TAG_NAME,
    OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME,
    COLUMN_NAME, TAG_VALUE, DOMAIN
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE TAG_NAME = 'DATA_CLASSIFICATION'
  AND OBJECT_DATABASE = 'FINSERV_DB'
ORDER BY OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME;

-- Policy coverage report: all policies in FINSERV_DB
SELECT
    POLICY_KIND, POLICY_NAME, POLICY_DB, POLICY_SCHEMA,
    REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
WHERE REF_DATABASE_NAME = 'FINSERV_DB'
ORDER BY POLICY_KIND, REF_ENTITY_NAME;

-- Query volume by role (last 7 days) — identifies unusual access patterns
SELECT
    ROLE_NAME,
    COUNT(*) AS QUERY_COUNT,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    SUM(CASE WHEN EXECUTION_STATUS = 'FAIL' THEN 1 ELSE 0 END) AS FAILED_QUERIES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND DATABASE_NAME = 'FINSERV_DB'
GROUP BY ROLE_NAME
ORDER BY QUERY_COUNT DESC;

-- DMF results: check latest data quality scores
SELECT
    MEASUREMENT_TIME,
    METRIC_DATABASE, METRIC_SCHEMA, METRIC_NAME,
    TABLE_DATABASE, TABLE_SCHEMA, TABLE_NAME,
    COLUMN_NAME, VALUE AS ISSUE_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_QUALITY_MONITORING_RESULTS
WHERE TABLE_DATABASE = 'FINSERV_DB'
ORDER BY MEASUREMENT_TIME DESC
LIMIT 20;


-- ============================================================
-- 10. GOVERNANCE DASHBOARD SUMMARY
--     Aggregate governance posture into a single table.
-- ============================================================

SELECT '>>> GOVERNANCE SUMMARY <<<' AS SECTION;

CREATE OR REPLACE TABLE CONSUMPTION.GOVERNANCE_SUMMARY AS

-- Tag coverage: count of classified vs total columns
WITH tag_coverage AS (
    SELECT
        COUNT(DISTINCT COLUMN_NAME) AS TAGGED_COLUMNS
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE TAG_NAME = 'DATA_CLASSIFICATION'
      AND OBJECT_DATABASE = 'FINSERV_DB'
      AND DOMAIN = 'COLUMN'
),
total_columns AS (
    SELECT COUNT(*) AS TOTAL_COLUMNS
    FROM FINSERV_DB.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA IN ('BASE', 'RAW', 'CURATED', 'CONSUMPTION')
),
policy_count AS (
    SELECT
        COUNT(DISTINCT CASE WHEN POLICY_KIND = 'MASKING_POLICY' THEN REF_COLUMN_NAME END) AS MASKED_COLUMNS,
        COUNT(DISTINCT CASE WHEN POLICY_KIND = 'ROW_ACCESS_POLICY' THEN REF_ENTITY_NAME END) AS RAP_TABLES
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE REF_DATABASE_NAME = 'FINSERV_DB'
)

SELECT
    CURRENT_TIMESTAMP()                                           AS ASSESSED_AT,
    tc.TAGGED_COLUMNS                                             AS CLASSIFIED_COLUMNS,
    tot.TOTAL_COLUMNS                                             AS TOTAL_COLUMNS,
    ROUND(tc.TAGGED_COLUMNS / NULLIF(tot.TOTAL_COLUMNS, 0) * 100, 1) AS CLASSIFICATION_PCT,
    pc.MASKED_COLUMNS                                             AS MASKED_COLUMN_COUNT,
    pc.RAP_TABLES                                                 AS ROW_ACCESS_TABLE_COUNT,
    5                                                             AS CUSTOM_ROLE_COUNT,
    4                                                             AS TAG_COUNT,
    5                                                             AS DMF_COUNT
FROM tag_coverage tc, total_columns tot, policy_count pc;

SELECT * FROM CONSUMPTION.GOVERNANCE_SUMMARY;

SELECT '>>> DATA GOVERNANCE MODULE COMPLETE <<<' AS STATUS;
